name: common_widget
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16 
  go_router: ^14.3.0
  toastification: ^2.3.0 

  # datetime 
  intl: ^0.20.2
  simple_gesture_detector: ^0.2.1
  # table_calendar: ^3.2.0

  
  # responsiveness
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 